### PR TITLE
Html5 Structure.

### PR DESCRIPTION
**Pull request by D31F43**
Init the structure of the webpage.

### CODE REVIEW

**Review by yvbbrjdr — APPROVED** [review]
Great design!

**Comment by bdbai** [comment]
Good work!
However inlining Javascript seems not a good idea. What about binding events using jQuery?

**Comment by yvbbrjdr** [comment]
> Good work!
However inlining Javascript seems not a good idea. What about binding events using jQuery?

I am not familiar with this, but isn't jQuery obsolete?

**Comment by D31F43** [comment]
jQuery might not be obsolete, thought the efficiency of it should be a huge problem. 
Reply to inline js: Using binding event to control navigating might not be beautiful? :) Anyway, binding is a better choice.

**Comment by bdbai** [comment]
jQuery's selector function, as well as other lightweight functions, has been optimized a lot. Thus performance won't be a problem. 
Although jQuery is not necessary with modern browsers, it will be more convenient to use it. 

@NHibiki Add a class 'nav-item' to all the navigation controls and try this
```javascript
$('.nav-item').click(e => {
  // Navigate here
});
```
It's up to you to choose the implementation :)

**Comment by yvbbrjdr** [comment]
Is it appropriate to load all the public resources (Roboto font, jQuery scripts, and any further ones) from github pages server, or from other sites providing this kind of service?

**Comment by bdbai** [comment]
@yvbbrjdr While GitHub Pages has had its CDN deployed worldwide, loading static resources from a public provider can be a good choice. 
I personally recommend bootcdn.cn with this CLI: [bootcdn-cli](https://github.com/bdbai/bootcdn-cli)

**Comment by yvbbrjdr** [comment]
@bdbai Can this project be imported directly to HTML?

**Comment by bdbai** [comment]
@yvbbrjdr Sure. Please watch [the demo](https://asciinema.org/a/ayf8gupozjtx4bwlqwugxh2bc) :P

**Comment by bdbai** [comment]
@yvbbrjdr Hey wait. How do you mean 'directly'?

**Comment by yvbbrjdr** [comment]
@bdbai <script>

**Comment by D31F43** [comment]
@bdbai Yeah, I've tried another approach. A bit different but works fine. It would be updated on next commit.

**Comment by bdbai** [comment]
@NHibiki Looking forward to your great work again :P
Btw HTML structure needs to be polished a little. For example, `li` tag should beneath `ul` immediately. `!DOCTYPE html` and `title` are also required by a complete HTML 5 doc.

**Pull request merged**
