### PR TITLE
Translation Mistake & Nav Responsive Fixed

### PR DESCRIPTION
**Pull request by D31F43**
```
 . Nav Responsive Fixed
 . Translation Mistake Fixed
```

---
Sat 18 Feb 12:39:59

### CODE REVIEW

**Comment by yvbbrjdr** [comment]
Lower pull request frequency.

**Comment by D31F43** [comment]
@yvbbrjdr but actually, it is an essential update 23333

**Comment by yvbbrjdr** [comment]
@NHibiki I have more to update

**Comment by D31F43** [comment]
@yvbbrjdr I should request again 2333. ( the problem is not a small one

**Comment by yvbbrjdr** [comment]
@NHibiki No nees for that. I can merge it anyway.

**Pull request merged**
